apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codify
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - codify.example.com
      secretName: codify-tls
  rules:
    - host: codify.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codify
                port:
                  name: http
