// Typed client for the `/v1/best-of-n` config endpoints. Mirrors the
// FastAPI routes serving the Best-of-N verifier configuration.
//
// Naming: TS surface is camelCase; the wire is snake_case. The
// converters below translate at the boundary so callers never see raw
// wire fields. Criteria ride as an ordered name → description record —
// JS objects preserve string-key insertion order, so the server's
// criteria ordering survives the round trip.

import { authenticatedFetch } from "./identity";

/** One proposal harness slot in the Best-of-N run configuration. */
export interface ProposerSpec {
  /** Harness slug, e.g. `"claude"` / `"codex"` / `"pi"`. */
  harness: string;
  enabled: boolean;
  /** Proposals generated by this harness per run. */
  count: number;
  /** Per-harness model override; `null` = the run-level proposal model. */
  model: string | null;
  /** Custom launch command override; `null` = the harness default. */
  command: string | null;
  /** Extra environment for the proposer process. */
  env: Record<string, string>;
}

/** Settings for the pairwise verifier that scores proposals. */
export interface VerifierSettings {
  model: string;
  baseUrl: string;
  apiKeyEnv: string;
  nEvaluations: number;
  pivots: number;
  seed: number;
  maxWorkers: number;
  /** What a failed comparison does: score 0.5/0.5 (`"tie"`) or abort (`"raise"`). */
  onError: "tie" | "raise";
}

/** The full Best-of-N run configuration (the PUT body's `config`). */
export interface BestOfNConfig {
  proposers: ProposerSpec[];
  /** Run-level default model for proposers without an override. */
  proposalModel: string;
  /** Ordered criterion name → description map. */
  criteria: Record<string, string>;
  verifier: VerifierSettings;
  proposalTimeoutS: number;
  keepProposalBranches: boolean;
}

/** GET/PUT `/v1/best-of-n/config` response, converted to camelCase. */
export interface BestOfNConfigResponse {
  config: BestOfNConfig;
  knownHarnesses: string[];
  /** Harness slug → whether its CLI is installed on the server. */
  harnessAvailability: Record<string, boolean>;
  /** Whether the verifier API key env var resolves on the server. */
  verifierKeyPresent: boolean;
  /** Ships with the response so "Restore defaults" needs no extra call. */
  defaultCriteria: Record<string, string>;
}

// ── Wire shapes ──────────────────────────────────────────────────────────────

interface ProposerSpecWire {
  harness: string;
  enabled: boolean;
  count: number;
  model?: string | null;
  command?: string | null;
  env?: Record<string, string>;
}

interface VerifierSettingsWire {
  model: string;
  base_url: string;
  api_key_env: string;
  n_evaluations: number;
  pivots: number;
  seed: number;
  max_workers: number;
  on_error: "tie" | "raise";
}

interface BestOfNConfigWire {
  proposers: ProposerSpecWire[];
  proposal_model: string;
  criteria: Record<string, string>;
  verifier: VerifierSettingsWire;
  proposal_timeout_s: number;
  keep_proposal_branches: boolean;
}

interface BestOfNConfigResponseWire {
  object: "best_of_n_config";
  config: BestOfNConfigWire;
  verifier_key_present?: boolean;
  known_harnesses: string[];
  harness_availability: Record<string, boolean>;
  default_criteria: Record<string, string>;
}

// ── Converters (exported for tests) ──────────────────────────────────────────

export function bestOfNConfigFromWire(wire: BestOfNConfigWire): BestOfNConfig {
  return {
    proposers: wire.proposers.map((p) => ({
      harness: p.harness,
      enabled: p.enabled,
      count: p.count,
      model: p.model ?? null,
      command: p.command ?? null,
      env: p.env ?? {},
    })),
    proposalModel: wire.proposal_model,
    criteria: { ...wire.criteria },
    verifier: {
      model: wire.verifier.model,
      baseUrl: wire.verifier.base_url,
      apiKeyEnv: wire.verifier.api_key_env,
      nEvaluations: wire.verifier.n_evaluations,
      pivots: wire.verifier.pivots,
      seed: wire.verifier.seed,
      maxWorkers: wire.verifier.max_workers,
      onError: wire.verifier.on_error,
    },
    proposalTimeoutS: wire.proposal_timeout_s,
    keepProposalBranches: wire.keep_proposal_branches,
  };
}

export function bestOfNConfigToWire(config: BestOfNConfig): BestOfNConfigWire {
  return {
    proposers: config.proposers.map((p) => ({
      harness: p.harness,
      enabled: p.enabled,
      count: p.count,
      model: p.model,
      command: p.command,
      env: p.env,
    })),
    proposal_model: config.proposalModel,
    criteria: { ...config.criteria },
    verifier: {
      model: config.verifier.model,
      base_url: config.verifier.baseUrl,
      api_key_env: config.verifier.apiKeyEnv,
      n_evaluations: config.verifier.nEvaluations,
      pivots: config.verifier.pivots,
      seed: config.verifier.seed,
      max_workers: config.verifier.maxWorkers,
      on_error: config.verifier.onError,
    },
    proposal_timeout_s: config.proposalTimeoutS,
    keep_proposal_branches: config.keepProposalBranches,
  };
}

export function bestOfNConfigResponseFromWire(
  wire: BestOfNConfigResponseWire,
): BestOfNConfigResponse {
  return {
    config: bestOfNConfigFromWire(wire.config),
    knownHarnesses: wire.known_harnesses,
    harnessAvailability: wire.harness_availability,
    // Absent on older servers — fail open so the launch form doesn't block.
    verifierKeyPresent: wire.verifier_key_present ?? true,
    defaultCriteria: { ...wire.default_criteria },
  };
}

// ── Requests ─────────────────────────────────────────────────────────────────

async function readResponseOrThrow(res: Response): Promise<BestOfNConfigResponse> {
  if (!res.ok) {
    // Surface the server's validation message (e.g. "criteria must not be
    // empty") over the bare status line when the body carries one.
    let message = `${res.status} ${res.statusText}`;
    try {
      const body = (await res.json()) as {
        detail?: string;
        error?: { message?: string };
      };
      if (body.error?.message) message = body.error.message;
      else if (typeof body.detail === "string" && body.detail) message = body.detail;
    } catch {
      // Non-JSON body — keep the status-line fallback.
    }
    throw new Error(message);
  }
  return bestOfNConfigResponseFromWire((await res.json()) as BestOfNConfigResponseWire);
}

/** GET /v1/best-of-n/config — the current configuration + metadata. */
export async function fetchBestOfNConfig(): Promise<BestOfNConfigResponse> {
  const res = await authenticatedFetch("/v1/best-of-n/config");
  return readResponseOrThrow(res);
}

/** PUT /v1/best-of-n/config — replace the configuration. */
export async function updateBestOfNConfig(config: BestOfNConfig): Promise<BestOfNConfigResponse> {
  const res = await authenticatedFetch("/v1/best-of-n/config", {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ config: bestOfNConfigToWire(config) }),
  });
  return readResponseOrThrow(res);
}
