apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: codify
  labels:
    app: codify
spec:
  host: codify.apps.example.com
  to:
    kind: Service
    name: codify
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
