# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codify/api/routing/v1/routing.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'codify/api/routing/v1/routing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#codify/api/routing/v1/routing.proto\x12\x15\x63odify.api.routing.v1\x1a\x1cgoogle/protobuf/struct.proto\"M\n\x0bRouteOption\x12\x12\n\x05model\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07harness\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_modelB\n\n\x08_harness\"r\n\rRouteSelector\x12\x18\n\x0brouter_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12,\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x01\x88\x01\x01\x42\x0e\n\x0c_router_nameB\t\n\x07_config\"\x99\x01\n\x0eRouteSelection\x12=\n\x0croute_option\x18\x01 \x01(\x0b\x32\".codify.api.routing.v1.RouteOptionH\x00\x88\x01\x01\x12,\n\x06params\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x01\x88\x01\x01\x42\x0f\n\r_route_optionB\t\n\x07_params\"&\n\x04Task\x12\x13\n\x06prompt\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_prompt\"\x9f\x01\n\x0bSessionTurn\x12.\n\x04task\x18\x01 \x01(\x0b\x32\x1b.codify.api.routing.v1.TaskH\x00\x88\x01\x01\x12\x43\n\x0froute_selection\x18\x02 \x01(\x0b\x32%.codify.api.routing.v1.RouteSelectionH\x01\x88\x01\x01\x42\x07\n\x05_taskB\x12\n\x10_route_selection\"K\n\x0eSessionHistory\x12\x39\n\rsession_turns\x18\x01 \x03(\x0b\x32\".codify.api.routing.v1.SessionTurn\"\xb7\x02\n\x12SelectRouteRequest\x12\x39\n\rroute_options\x18\x01 \x03(\x0b\x32\".codify.api.routing.v1.RouteOption\x12.\n\x04task\x18\x02 \x01(\x0b\x32\x1b.codify.api.routing.v1.TaskH\x00\x88\x01\x01\x12\x41\n\x0eroute_selector\x18\x03 \x01(\x0b\x32$.codify.api.routing.v1.RouteSelectorH\x01\x88\x01\x01\x12\x43\n\x0fsession_history\x18\x04 \x01(\x0b\x32%.codify.api.routing.v1.SessionHistoryH\x02\x88\x01\x01\x42\x07\n\x05_taskB\x11\n\x0f_route_selectorB\x12\n\x10_session_history\"{\n\x13SelectRouteResponse\x12>\n\x0froute_selection\x18\x01 \x03(\x0b\x32%.codify.api.routing.v1.RouteSelection\x12\x16\n\trationale\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_rationaleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codify.api.routing.v1.routing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEOPTION']._serialized_start=92
  _globals['_ROUTEOPTION']._serialized_end=169
  _globals['_ROUTESELECTOR']._serialized_start=171
  _globals['_ROUTESELECTOR']._serialized_end=285
  _globals['_ROUTESELECTION']._serialized_start=288
  _globals['_ROUTESELECTION']._serialized_end=441
  _globals['_TASK']._serialized_start=443
  _globals['_TASK']._serialized_end=481
  _globals['_SESSIONTURN']._serialized_start=484
  _globals['_SESSIONTURN']._serialized_end=643
  _globals['_SESSIONHISTORY']._serialized_start=645
  _globals['_SESSIONHISTORY']._serialized_end=720
  _globals['_SELECTROUTEREQUEST']._serialized_start=723
  _globals['_SELECTROUTEREQUEST']._serialized_end=1034
  _globals['_SELECTROUTERESPONSE']._serialized_start=1036
  _globals['_SELECTROUTERESPONSE']._serialized_end=1159
# @@protoc_insertion_point(module_scope)
