apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: codify-postgres
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: codify-postgres
    component: postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
